### ISSUE TITLE
How to add features to layers ?

### ISSUE THREAD

**Issue by kjll3r2002** [tombatossals/angular-openlayers-directive#168] opened 2015-08-12 18:54 UTC
This project is awesome too!
Thanks.....

**Comment by juristr** [comment] 2015-08-22 12:15
Hi, @kjll3r2002 ,
thx for your interest in this library. I think this is a duplicate of #145. If you're interested, please subscribe on that issue in order to get notified when it's resolved. I'm closing this one.

**Closed by juristr** 2015-08-22 12:15 UTC
Labels: question
