### ISSUE TITLE
Inconsistent binding of marker using ol-marker

### ISSUE THREAD

**Issue by achraibi** [tombatossals/angular-openlayers-directive#110] opened 2015-05-04 16:26 UTC
Hello,

In v.0.0.5, altering marker **coordinates** after they have been rendered with <ol-marker> directive does not reflect the changes in the map.

Here is a plunk demonstrating the issue : http://plnkr.co/edit/M1qm93gAhrGBbcnlxOOu?p=preview

How is it possible to achieve two way binding between openlayers markers and angular models ?

**Comment by achraibi** [comment] 2015-05-08 11:44
Hello,
Here is another plunk demonstrating similar binding issue: http://plnkr.co/edit/oHzLdlUNiEnHZKYA6qdK?p=preview
Notice all markers get removed from the map only when the markers array is completely cleared

**Comment by zzats** [comment] 2015-05-15 13:17
This is partly fixed by adding a removeFeature to the $destroy -listener of the marker scope.

Didn't find the cause of the missing labels yet.

**Comment by quentinlampin** [comment] 2015-06-25 17:02
Hello,
The first issue that @achraibi reported seems not to be fixed, i.e. altering marker coordinates after they have been rendered with directive does not reflect the changes in the map.

Here is a(nother) plunker that exhibits the issue: 

http://plnkr.co/edit/mNhWcV42LnnsaHGS4VbD?p=preview

In this plunker, I set up a simple map controller with a collection of nodes. For each node, I'm using the ol-marker directive to render a marker on the map.

 I'm using $interval to modify node1's location and node2's message every 3s. Node2's message changes are reflected on the map, i.e. the label does change, while node1's marker stays at its original location. I was expecting node1's marker position to be updated every 3s.

Should I open a new issue for this or is it still in the scope of this one?

Regards,

Quentin

**Comment by juristr** [comment] 2016-06-10 12:16
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).

**Closed by juristr** 2016-06-10 12:16 UTC
Labels: bug
